### ISSUE TITLE
Unable to connect wallet

### ISSUE THREAD

**Issue by expocmak** [beyond-btc/feedback#30]
### Contact details

https://x.com/expocmak

### What happened?

Unable to connect my evm wallet

Everything fine with UniSat btc wallet, but Metamask evm connection dont work at all
Tried reload site and browser, metamask is unlocked and i can connect to other sites

By the way i did the BTC-EVM transaction just after i enter my adress below 
So transactions work fine, dont have lags and other issues, design is beautiful and simple to understand
Great useful product, i like it

Please check the EVM connection issue
U can ask details if u need

**Comment by expocmak** [comment]
I used Chrome browser)

**Comment by Julietnacy** [comment]
@expocmak It sounds like everything is working fine with your UniSat BTC wallet, but the MetaMask EVM connection is giving you trouble. Since you've already reloaded the site and browser and confirmed that MetaMask is unlocked and working with other sites, it might be a specific issue with the platform you're trying to connect to. I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Insufficient info to work with.
