### ISSUE TITLE
Can't send tokens

### ISSUE THREAD

**Issue by Ebanizver** [beyond-btc/feedback#4]
### Contact details

Lev12345kek@yandex.ru

### What happened?

<img width="398" alt="Снимок экрана 2024-10-17 в 15 20 08" src="https://github.com/user-attachments/assets/f1d540fe-a06b-4ad3-b544-5bf38cbc2c88">
<img width="509" alt="Снимок экрана 2024-10-17 в 15 19 56" src="https://github.com/user-attachments/assets/0b941118-5f70-43eb-b7d8-c042eeb47187">
I keep getting an error that I can't transfer 0.01 ETH. I can't figure out what the issue is. The balance is there, and I've attached a screenshot as proof. I also refreshed the page, re-linked my wallets, and tried sending a different amount

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by theo-beyond** [comment]
For the first transfer, it looks like you used a mainnet address instead of a testnet one. That’s likely why it failed.

For the error, please attach a screenshot of the browser’s console, and your metamask balance (I think its because the value + bridge fee is higher than your balance) (for console: press F12 or right-click, then select ‘Inspect’ and navigate to the ‘Console’ tab on the top bar of the newly opened window).

**Comment by Ebanizver** [comment]
<img width="516" alt="Снимок экрана 2024-10-17 в 15 36 05" src="https://github.com/user-attachments/assets/387fe193-72a4-4f96-ad55-72a501014229">
Transaction successful, it was likely a system display bug

**Comment by Ebanizver** [comment]
Found a couple more things that would be great to add. I’ll write them down later

**Comment by theo-beyond** [comment]
Thanks! That modal is made of mock data, please don't mind the informations displayed there 😃

**Comment by sunnybeyond** [comment]
@Ebanizver Keeping this open for now for further writeup by you.
