### ISSUE TITLE
Feedback on Beyond Tech

### ISSUE THREAD

**Issue by Only1dreezy** [beyond-btc/feedback#8]
I have the chance to test out Beyond Tech's bridge dApp, and while there are some great features, I ran into a few issues that might need attention:

Wallet Connection Issues: When I tried connecting my wallet on my laptop, it wouldn’t work. However, when I switched to my iPhone, it connected fine. I’m not sure if it’s an issue with my laptop or the dApp, but it’s something worth checking out.

Price Mismatch: When I tried bridging, I noticed the ETH amount I entered didn’t match the equivalent amount in USD. This might cause confusion, so it would be helpful to look into this discrepancy.

Swapping Problem: I attempted to swap 0.04 ETH to BTC, but it failed, saying, “Couldn't send 0.04 ETH from Sepolia Testnet to BTC testnet, please try again or ask for support.” I also tried bridging to BNB with no luck, and got the same error. Not sure if the amount was too small, but it’s something that might need tweaking.

Overall, I think these are areas worth rectifying to improve the user experience.

**Comment by Only1dreezy** [comment]
![IMG_4814](https://github.com/user-attachments/assets/f4e70f94-7556-4036-9795-eabaa32cf9f0)

**Comment by Julietnacy** [comment]
@Only1dreezy Since your wallet connects fine on your iPhone but not on your laptop, it might be a compatibility issue with the browser or the wallet extension on your laptop. I'll have to refer you to the official support live chat with the ticket ID BEY07638
Please see the link below to our dedicated support line:
[Beyond tech Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Not enough information to work with. Price is known, this is due to being testnet.
